### ISSUE TITLE
Docker Compose File

### ISSUE THREAD

**Issue by aBuder** [yep/usergrid-docker#6]
Hi, 

is it possible to get an Docker Compose file to startup file

**Comment by YMonnier** [comment]
```yml
version: '3'

services:
  cassandra:
    image: yep1/usergrid-cassandra
    volumes:
      - ./data/cassandra:/var/lib/cassandra
  elasticsearch:
    image: yep1/usergrid-elasticsearch
    volumes:
      - ./data/elasticsearch:/data
  usergrid:
    image: yep1/usergrid
    environment:
      ADMIN_PASS: SuperTest
      ORG_NAME: orgNameTest
      APP_NAME: appNameTest
      CASSANDRA_PORT_9160_TCP_ADDR: cassandra
      CASSANDRA_PORT_9160_TCP_PORT: 9160
      ELASTICSEARCH_PORT_9300_TCP_ADDR: elasticsearch
      ELASTICSEARCH_PORT_9300_TCP_PORT: 9300
```
